package com.ronaldong.messi;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ATTACHMENT".
 */
public class Attachment {

    private Long id;
    private Long messageId;
    private String type;
    private String title;
    private String content;
    private String url;
    private String duration;
    private String localPath;

    public Attachment() {
    }

    public Attachment(Long id) {
        this.id = id;
    }

    public Attachment(Long id, Long messageId, String type, String title, String content, String url, String duration, String localPath) {
        this.id = id;
        this.messageId = messageId;
        this.type = type;
        this.title = title;
        this.content = content;
        this.url = url;
        this.duration = duration;
        this.localPath = localPath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMessageId() {
        return messageId;
    }

    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getLocalPath() {
        return localPath;
    }

    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }

}
