package com.ronaldong.messi;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORGANIZE".
 */
public class Organize {

    private Long id;
    private String name;
    private String pinyin;
    private String avatar;
    private Integer indexOrder;
    private String organizeType;
    private String deleted;
    private Long parentId;
    private Long lut;

    public Organize() {
    }

    public Organize(Long id) {
        this.id = id;
    }

    public Organize(Long id, String name, String pinyin, String avatar, Integer indexOrder, String organizeType, String deleted, Long parentId, Long lut) {
        this.id = id;
        this.name = name;
        this.pinyin = pinyin;
        this.avatar = avatar;
        this.indexOrder = indexOrder;
        this.organizeType = organizeType;
        this.deleted = deleted;
        this.parentId = parentId;
        this.lut = lut;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getIndexOrder() {
        return indexOrder;
    }

    public void setIndexOrder(Integer indexOrder) {
        this.indexOrder = indexOrder;
    }

    public String getOrganizeType() {
        return organizeType;
    }

    public void setOrganizeType(String organizeType) {
        this.organizeType = organizeType;
    }

    public String getDeleted() {
        return deleted;
    }

    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public Long getLut() {
        return lut;
    }

    public void setLut(Long lut) {
        this.lut = lut;
    }

}
