package com.ronaldong.messi;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORGANIZE".
*/
public class OrganizeDao extends AbstractDao<Organize, Long> {

    public static final String TABLENAME = "ORGANIZE";

    /**
     * Properties of entity Organize.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Pinyin = new Property(2, String.class, "pinyin", false, "PINYIN");
        public final static Property Avatar = new Property(3, String.class, "avatar", false, "AVATAR");
        public final static Property IndexOrder = new Property(4, Integer.class, "indexOrder", false, "INDEX_ORDER");
        public final static Property OrganizeType = new Property(5, String.class, "organizeType", false, "ORGANIZE_TYPE");
        public final static Property Deleted = new Property(6, String.class, "deleted", false, "DELETED");
        public final static Property ParentId = new Property(7, Long.class, "parentId", false, "PARENT_ID");
        public final static Property Lut = new Property(8, Long.class, "lut", false, "LUT");
    };


    public OrganizeDao(DaoConfig config) {
        super(config);
    }
    
    public OrganizeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORGANIZE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"PINYIN\" TEXT," + // 2: pinyin
                "\"AVATAR\" TEXT," + // 3: avatar
                "\"INDEX_ORDER\" INTEGER," + // 4: indexOrder
                "\"ORGANIZE_TYPE\" TEXT," + // 5: organizeType
                "\"DELETED\" TEXT," + // 6: deleted
                "\"PARENT_ID\" INTEGER," + // 7: parentId
                "\"LUT\" INTEGER);"); // 8: lut
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORGANIZE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Organize entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String pinyin = entity.getPinyin();
        if (pinyin != null) {
            stmt.bindString(3, pinyin);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(4, avatar);
        }
 
        Integer indexOrder = entity.getIndexOrder();
        if (indexOrder != null) {
            stmt.bindLong(5, indexOrder);
        }
 
        String organizeType = entity.getOrganizeType();
        if (organizeType != null) {
            stmt.bindString(6, organizeType);
        }
 
        String deleted = entity.getDeleted();
        if (deleted != null) {
            stmt.bindString(7, deleted);
        }
 
        Long parentId = entity.getParentId();
        if (parentId != null) {
            stmt.bindLong(8, parentId);
        }
 
        Long lut = entity.getLut();
        if (lut != null) {
            stmt.bindLong(9, lut);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Organize readEntity(Cursor cursor, int offset) {
        Organize entity = new Organize( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // pinyin
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // avatar
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // indexOrder
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // organizeType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // deleted
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // parentId
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // lut
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Organize entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPinyin(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAvatar(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIndexOrder(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setOrganizeType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDeleted(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setParentId(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setLut(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Organize entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Organize entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
