package com.ronaldong.messi;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WORK_GROUP".
 */
public class WorkGroup {

    private Long id;
    private String name;
    private String pinyin;
    private String avatar;
    private Integer indexOrder;
    private String groupType;
    private String deleted;
    private Long lut;
    private String isPublic;
    private String isTmp;
    private String tagId;
    private String canEdit;

    public WorkGroup() {
    }

    public WorkGroup(Long id) {
        this.id = id;
    }

    public WorkGroup(Long id, String name, String pinyin, String avatar, Integer indexOrder, String groupType, String deleted, Long lut, String isPublic, String isTmp, String tagId, String canEdit) {
        this.id = id;
        this.name = name;
        this.pinyin = pinyin;
        this.avatar = avatar;
        this.indexOrder = indexOrder;
        this.groupType = groupType;
        this.deleted = deleted;
        this.lut = lut;
        this.isPublic = isPublic;
        this.isTmp = isTmp;
        this.tagId = tagId;
        this.canEdit = canEdit;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Integer getIndexOrder() {
        return indexOrder;
    }

    public void setIndexOrder(Integer indexOrder) {
        this.indexOrder = indexOrder;
    }

    public String getGroupType() {
        return groupType;
    }

    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }

    public String getDeleted() {
        return deleted;
    }

    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

    public Long getLut() {
        return lut;
    }

    public void setLut(Long lut) {
        this.lut = lut;
    }

    public String getIsPublic() {
        return isPublic;
    }

    public void setIsPublic(String isPublic) {
        this.isPublic = isPublic;
    }

    public String getIsTmp() {
        return isTmp;
    }

    public void setIsTmp(String isTmp) {
        this.isTmp = isTmp;
    }

    public String getTagId() {
        return tagId;
    }

    public void setTagId(String tagId) {
        this.tagId = tagId;
    }

    public String getCanEdit() {
        return canEdit;
    }

    public void setCanEdit(String canEdit) {
        this.canEdit = canEdit;
    }

}
